[[inputs.ceph]]
  interval = "1m"
  ceph_binary = "/usr/bin/ceph"
  socket_dir = "/var/run/ceph"
  mon_prefix = "ceph-mon"
  osd_prefix = "ceph-osd"
  mds_prefix = "ceph-mds"
  rgw_prefix = "ceph-client"
  socket_suffix = "asok"
  ceph_user = "client.admin"
  ceph_config = "/etc/ceph/ceph.conf"
  gather_admin_socket_stats = true
  gather_cluster_stats = false

