[[inputs.filestat]]
  files = ["/etc/pve/**"]
  md5 = false

[[inputs.proxmox]]
  base_url = "https://$PROXMOX_URL:8006/api2/json"
  api_token = "$PROXMOX_TOKEN"

[[inputs.procstat]]
  exe = "corosync"

[[inputs.procstat]]
  exe = "pmxcfs"

[[inputs.procstat]]
  exe = "proxmox"

[[inputs.procstat]]
  exe = "pve"

[[inputs.procstat]]
  exe = "spiceproxy"

