[[inputs.filestat]]
  files = ["/etc/samba/smb.conf", "/var/lib/samba/**.tdb"]
  md5 = false

[[inputs.procstat]]
  exe = "nmbd"

[[inputs.procstat]]
  exe = "smbd"

[[inputs.procstat]]
  exe = "winbindd"

